OnlineJudge/urls.py
from django.contrib import admin
from django.urls import path, include
# from googleauthentication import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',include("googleauthentication.urls")),
    path('account/',include("allauth.urls")),
    path('',include('home.urls')),
    path('',include('User.urls')),
]

User/urls.py
from django.urls import path
from . import views
app_name ='User'
urlpatterns = [
    path('',views.loginpage, name='loginpage'),
    path('register/',views.registerpage, name='registerpage'),
]

home/urls.py
from django.urls import path
from . import views
app_name ='home'
urlpatterns = [
    path('List/',views.ProblemListView.as_view(), name='Problemset'),
    path('List/<int:problem_id>/',views.ProblemDetail, name='problempage'),
    path('List/<int:problem_id>/verdict/',views.Verdict, name='verdict'),
]

home/models.py
import datetime
from django.db import models
from django.utils import timezone

class Problem(models.Model):
    problem_name=models.CharField(max_length=200)
    problem_statement=models.CharField(max_length=2000)
    def __str__(self):
        return self.problem_name
class TestCase(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    input = models.TextField()
    output = models.TextField()

    def __str__(self):
        return ("TC: " + str(self.id) + " for Problem: " + str(self.problem))

home/forms.py
from django import forms
from django.forms import ModelForm
from User.models import Submission

class CodeForm(ModelForm):
    class Meta:
        model = Submission
        fields = ['user_code','language']
        widgets = {'user_code' : forms.Textarea()}

home/views.py
from .models import Problem,TestCase
from User.models import Submission
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from home.forms import CodeForm
from django.views import generic
from time import time
import os
import signal
import subprocess
import os.path
import docker

class ProblemListView(generic.ListView):
    template_name = 'home\Problemset.html'
    context_object_name = 'Problem_list'

    def get_queryset(self):
        return Problem.objects.all()
def ProblemDetail(request, problem_id):
    problem = get_object_or_404(Problem, id=problem_id)
    form = CodeForm()
    context = {
        'ProblemName': problem.problem_name,
        'Problemstatement': problem.problem_statement,
        'problem_id': id,
        'problem': problem,
    }
    return render(request, 'home\problempage.html', context)

def Verdict(request, problem_id):
    # extract data from form
    form = CodeForm(request.POST)
    user_code = 'Not_valid'
    if  form.is_valid():
        instance = form.save(commit=False)
        user_code = form.cleaned_data.get('user_code')
        user_code = user_code.replace('\r\n','\n').strip()
        instance.save()
    else :
        print(form.errors)

    # user_code=request.POST['user_code']    
    language = request.POST['language']
    
    if request.method == 'POST':
        # setting docker-client
        docker_client = docker.from_env()
        Running = "running"
        problem = Problem.objects.get(id=problem_id)
        testcase = TestCase.objects.get(problem_id=problem_id)
        #replacing \r\n by \n in original output to compare it with the usercode output
        testcase.output = testcase.output.replace('\r\n','\n').strip() 
        filename=str(problem.id)
        # print(filename)
        if language == "C++":
                extension = ".cpp"
                cont_name = "oj-cpp"
                compile = f"g++  {filename}.cpp"
                clean = f" {filename}.cpp"
                docker_img = "gcc:11.2.0"
                exe = f"./{filename}.out"
        file = filename + extension
        filepath = settings.FILES_DIR + "/" + file
        code = open(filepath,"w")
        code.write(user_code)
        code.close()
        print("sending usercode to :"+filepath)
        # checking if the docker container is running or not
        try:
            container = docker_client.containers.get(cont_name)
            container_state = container.attrs['State']
            container_is_running = (container_state['Status'] == Running)
            if not container_is_running:
                subprocess.run(f"docker start {cont_name}",shell=True)
        except docker.errors.NotFound:
            subprocess.run(f"docker run -dt --name {cont_name} {docker_img}",shell=True)
        res="Not compiled"
        verdict="Wrong Answer"
         # copy/paste the .cpp file in docker container 
        
        t=subprocess.run(f"docker cp {filepath} {cont_name}:/{file}",shell=True)
        # if(file):
            # print("q",file)
            # print("p",filepath)
            # subprocess.run(f"docker cp {filepath} {cont_name}:/{file}",shell=True)
        # compiling the code
        cmp = subprocess.run(f"docker exec {cont_name} {compile}", capture_output=True, shell=True)
        if(cmp):
            print("cmp",cmp)
        if cmp.returncode != 0:
            verdict = "Compilation Error"
            run_time="Not compiled"
            # subprocess.run(f"docker exec {cont_name} rm {file}",shell=True)

        else:
            # running the code on given input and taking the output in a variable in bytes
            start = time()
            try:
                begin=time()
                res = subprocess.run( f'docker exec -it {cont_name} sh -c "echo \'{testcase.input}\' | ./a.out"' ,
                                                capture_output=True, timeout=10,shell=True)
                # res = subprocess.run(f" docker exec -it  {cont_name} sh -c "echo "5 4 3 2 1" | {exe}.out" ",
                #                                 capture_output=True, timeout=100000, shell=True)
                if(res):
                    print("result",res)
                run_time = time()-start
                print("time",run_time)
                subprocess.run(f"docker exec {cont_name} rm {clean}",shell=True)
            except subprocess.TimeoutExpired:
                run_time = time()-start
                print("exceeded")
                verdict = "Time Limit Exceeded"
                subprocess.run(f"docker container kill {cont_name}", shell=True)
                subprocess.run(f"docker start {cont_name}",shell=True)
                subprocess.run(f"docker exec {cont_name} rm {clean}",shell=True)
            if verdict != "Time Limit Exceeded" and res.returncode != 0:
                verdict = "Runtime Error"
                

        user_stderr = ""
        user_stdout = ""
        if verdict == "Compilation Error":
            user_stderr = cmp.stderr.decode('utf-8')
        
        elif verdict == "Wrong Answer":
            print("expected",testcase.output)
            user_stdout = res.stdout.decode('utf-8')
            print("useroutput",user_stdout)
            if str(user_stdout)==str(testcase.output):
                verdict = "Accepted"
            testcase.output += '\n' # added extra line to compare user output having extra line at the end of their output
            if str(user_stdout)==str(testcase.output):
                verdict = "Accepted"
        instance.problem=problem
        instance.verdict=verdict
        if request.user.is_authenticated:
            instance.user=request.user
        instance.save()
        
        print(instance)
        context={
        'Code': user_code,
        'lang': language,
        'res':res,
        'verdict':verdict,
        'user_stderr':user_stderr,
        'user_stdout': user_stdout,
        'time':run_time
        }
                
    return render(request, 'home\problemverdict.html', context)

home/templates/home/Problemset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problems</title>
</head>
<body>
    <h1>My_OJ</h1>
    <h2>Choose the problem to solve</h2>
    {% csrf_token %}
    {% if Problem_list %}
    <ul>
    {% for problem in Problem_list %}
    <li><a href="{% url 'home:problempage' problem.id %}">{{ problem.problem_name }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No problems are available.</p>
    {% endif %}
</body>
</html>

home/templates/home/problempage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ProblemName}}</title>
    <style>
        #Problemstatement {
            border: 2px solid black;
            height: 300px;
            width: 100%;
            margin: 5px;
        }

        #code {
            border: 2px solid black;
            height: 400px;
            width: 50%;
            margin: 5px;
        }
        #rowbox{
            display: flex;
            flex-direction: row;
        }
        #flexbox {
            display: flex;
            flex-direction: column;
        }

        .iov {
            border: 2px solid black;
            height: 500px;
            width: 300%;
            margin: 5px;
        }
        .code-editor-box,
    </style>
</head>

<body>
    <h1>My_OJ</h1>
    <h2>All the best</h2>
    <h3>{{ProblemName}}</h3>
        <p id="Problemstatement">
            {{Problemstatement}}

        </p>
        <form action="{% url 'home:verdict' problem.id %}" method="POST" enctype="multipart/form-data">
        
        {% csrf_token %}
        <div id="rowbox">
            <div id="flexbox">
                <select name='language'>
                    <option>C++</option>
                    <option>C</option>
                    <option>Python</option>
                </select>
                <div class="code-editor-box">
                    <h2>Code Editor</h2>
                    <textarea name='user_code' rows="20" cols="100"></textarea>
                </div>
            </div>
            <div id="flexbox">
                <h5 class="iov">Verdict
                    <p>
                        {% comment %} <li>code:{{Code}}</li> {% endcomment %}
                        {% comment %} <li>lang:{{lang}}</li> {% endcomment %}
                        {% comment %} <li>res:{{res}}</li> {% endcomment %}
                        <li>verdict:{{verdict}}</li>
                        {{user_stderr}}
                        {% comment %} <li> user_stdout:{{user_stdout}}</li> {% endcomment %}
                        {% comment %} <li>verdict:{{user_stderr}}</li> {% endcomment %}
                    </p>
                </h5>
                <button type="submit">Submit</button>
            </div>
        </div>
    </form>
    <script>

    </script>
</body>
</html>

home/templates/home/problemverdict.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verdict</title>
</head>
<body>
    <h1>My_OJ</h1>
    <h2>Verdict</h2>
    <p>
        {% comment %} <li>code:{{Code}}</li> {% endcomment %}
        {% comment %} <li>lang:{{lang}}</li> {% endcomment %}
        {% comment %} <li>res:{{res}}</li> {% endcomment %}
        <li>verdict:{{verdict}}</li>
        {{user_stderr}}
        {% comment %} <li> user_stdout:{{user_stdout}}</li> {% endcomment %}
        {% comment %} <li>verdict:{{user_stderr}}</li> {% endcomment %}
    </p>
    <button><a href="{% url 'home:Problemset' %}">Go back to ProblemList</a></button>
</body>
</html>